title: Responsive Web Design Kent State
email: challahan@ideabasekent.com
description: "Classes and Workshops on Responsive Web Design from Kent State University"
url: "https://rwdkent.com" # the base hostname & protocol for your site
enforce_ssl: www.rwdkent.com   # without any protocol
future: true

collections:
 groups:
   output: true
   permalink: /class/groups/:path/
 classes:
   output: true
   permalink: /class/schedule/:path/
 assignments:
   output: true
   permalink: /class/assignments/:path/
 assignments_arwd:
   output: true
   permalink: /advanced/assignments/:path/
 classes_arwd:
   output: false
 groups_arwd:
   output: false
